import tkinter as tk
from tkinter import messagebox
import cv2
import numpy as np

def validar():
# aqui cree las sentencias if donde llama a  una funcion y crea cada probabilidad que aparezca.
#Entonces una compleja no agarra, solamente sencillas. Se puden complejas pero igual abria que hacer todas las probabilidades.
#------- (+)
    if entrada1.get()=="P+Q":

        win=tk.Toplevel()
        win.geometry("400x280+400+400")
        win.configure(background="dark turquoise")
        a3=tk.Label(win,text="Tabla P+Q")
        a3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        a3=tk.Label(win,text="P                      1                    P+Q")
        a3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        a3=tk.Label(win,text="0                      0                     0")
        a3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        a3=tk.Label(win,text="0                      1                     1")
        a3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        a3=tk.Label(win,text="1                      0                     1")
        a3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        a3=tk.Label(win,text="1                      1                     0")
        a3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        
        imagen=cv2.imread("i.png",1)
        cv2.imshow("IMAGEN",imagen)
        cv2.waitKey(0)
        cv2.destroyAllWindows()
        
    if entrada1.get()=="P+R":
        win=tk.Toplevel()
        win.geometry("400x400+400+400")
        win.configure(background="dark turquoise")
        boton2=tk.Button(win,text="close",command=win.destroy)
        boton2.pack(side=tk.TOP)
        e3=tk.Label(win,text="tabla")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="P                      R                   P+R")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      F                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      V                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        ima=cv2.imread("Es.png",1)
        cv2.imshow("IMAGEN",ima)
        cv2.waitKey(0)
        cv2.destroyAllWindows()
        
    if entrada1.get()=="P+S":
         abrirventana28()
    if entrada1.get()=="Q+P":
         abrirventana29()
    if entrada1.get()=="Q+R":
         abrirventana30()
    if entrada1.get()=="Q+S":
         abrirventana31()
    if entrada1.get()=="R+Q":
         abrirventana32()
    if entrada1.get()=="R+P":
         abrirventana33()
    if entrada1.get()=="R+S":
         abrirventana34()
    if entrada1.get()=="S+Q":
         abrirventana35()
    if entrada1.get()=="S+P":
         abrirventana36()
    if entrada1.get()=="S+R":
         abrirventana37()
#-------- (->)
    if entrada1.get()=="P→Q":
         abrirventana38()
    if entrada1.get()=="P→R":
         abrirventana39()
    if entrada1.get()=="P→S":
         abrirventana40()
    if entrada1.get()=="Q→P":
         abrirventana41()
    if entrada1.get()=="Q→R":
         abrirventana42()
    if entrada1.get()=="Q→S":
         abrirventana43()
    if entrada1.get()=="R→Q":
         abrirventana44()
    if entrada1.get()=="R→P":
         abrirventana45()
    if entrada1.get()=="R→S":
         abrirventana46()
    if entrada1.get()=="S→Q":
         abrirventana47()
    if entrada1.get()=="S→P":
         abrirventana48()
    if entrada1.get()=="S→R":
         abrirventana49()
#---------  (<->)
    if entrada1.get()=="P↔Q":
         abrirventana50()
    if entrada1.get()=="P↔R":
         abrirventana51()
    if entrada1.get()=="P↔S":
         abrirventana52()
    if entrada1.get()=="Q↔P":
         abrirventana53()
    if entrada1.get()=="Q↔R":
         abrirventana54()
    if entrada1.get()=="Q↔S":
         abrirventana55()
    if entrada1.get()=="R↔Q":
         abrirventana56()
    if entrada1.get()=="R↔P":
         abrirventana57()
    if entrada1.get()=="R↔S":
         abrirventana58()
    if entrada1.get()=="S↔Q":
         abrirventana59()
    if entrada1.get()=="S↔P":
         abrirventana60()
    if entrada1.get()=="S↔R":
         abrirventana61()
#se muestra las funciones 
#---------  (+)
    

def abrirventana28():

        
        e3=tk.Label(win,text="tabla")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="P                      S                   P+S")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      F                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      V                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)

def abrirventana29():
        win=tk.Toplevel()
        win.geometry("400x400+400+400")
        win.configure(background="dark turquoise")
        boton2=tk.Button(win,text="close",command=win.destroy)
        boton2.pack(side=tk.TOP)
        e3=tk.Label(win,text="tabla")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="Q                      P                   Q+P")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      F                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      V                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)

def abrirventana30():
        win=tk.Toplevel()
        win.geometry("400x400+400+400")
        win.configure(background="dark turquoise")
        boton2=tk.Button(win,text="close",command=win.destroy)
        boton2.pack(side=tk.TOP)
        e3=tk.Label(win,text="tabla")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="Q                      R                   Q+R")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      F                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      V                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
def abrirventana31():
        win=tk.Toplevel()
        win.geometry("400x400+400+400")
        win.configure(background="dark turquoise")
        boton2=tk.Button(win,text="close",command=win.destroy)
        boton2.pack(side=tk.TOP)
        e3=tk.Label(win,text="tabla")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="Q                      S                   Q+S")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      F                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      V                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
def abrirventana32():
        win=tk.Toplevel()
        win.geometry("400x400+400+400")
        win.configure(background="dark turquoise")
        boton2=tk.Button(win,text="close",command=win.destroy)
        boton2.pack(side=tk.TOP)
        e3=tk.Label(win,text="tabla")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="R                      Q                   R+Q")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      F                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      V                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
def abrirventana33():
        win=tk.Toplevel()
        win.geometry("400x400+400+400")
        win.configure(background="dark turquoise")
        boton2=tk.Button(win,text="close",command=win.destroy)
        boton2.pack(side=tk.TOP)
        e3=tk.Label(win,text="tabla")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="R                      P                   R+P")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      V                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
def abrirventana34():
        win=tk.Toplevel()
        win.geometry("400x400+400+400")
        win.configure(background="dark turquoise")
        boton2=tk.Button(win,text="close",command=win.destroy)
        boton2.pack(side=tk.TOP)
        e3=tk.Label(win,text="tabla")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="R                      S                   R+S")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      F                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      V                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
def abrirventana35():
        win=tk.Toplevel()
        win.geometry("400x400+400+400")
        win.configure(background="dark turquoise")
        boton2=tk.Button(win,text="close",command=win.destroy)
        boton2.pack(side=tk.TOP)
        e3=tk.Label(win,text="tabla")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="S                      Q                   S+Q")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      F                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      V                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
def abrirventana36():
        win=tk.Toplevel()
        win.geometry("400x400+400+400")
        win.configure(background="dark turquoise")
        boton2=tk.Button(win,text="close",command=win.destroy)
        boton2.pack(side=tk.TOP)
        e3=tk.Label(win,text="tabla")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="S                      P                   S+P")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      F                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      V                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)

def abrirventana37():
        win=tk.Toplevel()
        win.geometry("400x400+400+400")
        win.configure(background="dark turquoise")
        boton2=tk.Button(win,text="close",command=win.destroy)
        boton2.pack(side=tk.TOP)
        e3=tk.Label(win,text="tabla")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="S                      R                   S+R")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      F                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      V                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
#-----------  (->)
def abrirventana38():
        win=tk.Toplevel()
        win.geometry("400x400+400+400")
        win.configure(background="dark turquoise")
        boton2=tk.Button(win,text="close",command=win.destroy)
        boton2.pack(side=tk.TOP)
        e3=tk.Label(win,text="tabla")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="P                      Q                   P→Q")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      F                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)

def abrirventana39():
        win=tk.Toplevel()
        win.geometry("400x400+400+400")
        win.configure(background="dark turquoise")
        boton2=tk.Button(win,text="close",command=win.destroy)
        boton2.pack(side=tk.TOP)
        e3=tk.Label(win,text="tabla")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="P                      R                   P→R")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      F                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)

def abrirventana40():
        win=tk.Toplevel()
        win.geometry("400x400+400+400")
        win.configure(background="dark turquoise")
        boton2=tk.Button(win,text="close",command=win.destroy)
        boton2.pack(side=tk.TOP)
        e3=tk.Label(win,text="tabla")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="P                      S                   P→S")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      F                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)

def abrirventana41():
        win=tk.Toplevel()
        win.geometry("400x400+400+400")
        win.configure(background="dark turquoise")
        boton2=tk.Button(win,text="close",command=win.destroy)
        boton2.pack(side=tk.TOP)
        e3=tk.Label(win,text="tabla")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="Q                      P                   Q→P")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      F                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)

def abrirventana42():
        win=tk.Toplevel()
        win.geometry("400x400+400+400")
        win.configure(background="dark turquoise")
        boton2=tk.Button(win,text="close",command=win.destroy)
        boton2.pack(side=tk.TOP)
        e3=tk.Label(win,text="tabla")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="Q                      R                   Q→R")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      F                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
def abrirventana43():
        win=tk.Toplevel()
        win.geometry("400x400+400+400")
        win.configure(background="dark turquoise")
        boton2=tk.Button(win,text="close",command=win.destroy)
        boton2.pack(side=tk.TOP)
        e3=tk.Label(win,text="tabla")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="Q                      S                   Q→S")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      F                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
def abrirventana44():
        win=tk.Toplevel()
        win.geometry("400x400+400+400")
        win.configure(background="dark turquoise")
        boton2=tk.Button(win,text="close",command=win.destroy)
        boton2.pack(side=tk.TOP)
        e3=tk.Label(win,text="tabla")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="R                      Q                   R→Q")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      F                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
def abrirventana45():
        win=tk.Toplevel()
        win.geometry("400x400+400+400")
        win.configure(background="dark turquoise")
        boton2=tk.Button(win,text="close",command=win.destroy)
        boton2.pack(side=tk.TOP)
        e3=tk.Label(win,text="tabla")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="R                      P                   R→P")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
def abrirventana46():
        win=tk.Toplevel()
        win.geometry("400x400+400+400")
        win.configure(background="dark turquoise")
        boton2=tk.Button(win,text="close",command=win.destroy)
        boton2.pack(side=tk.TOP)
        e3=tk.Label(win,text="tabla")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="R                      S                   R→S")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      F                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
def abrirventana47():
        win=tk.Toplevel()
        win.geometry("400x400+400+400")
        win.configure(background="dark turquoise")
        boton2=tk.Button(win,text="close",command=win.destroy)
        boton2.pack(side=tk.TOP)
        e3=tk.Label(win,text="tabla")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="S                      Q                   S→Q")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      F                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
def abrirventana48():
        win=tk.Toplevel()
        win.geometry("400x400+400+400")
        win.configure(background="dark turquoise")
        boton2=tk.Button(win,text="close",command=win.destroy)
        boton2.pack(side=tk.TOP)
        e3=tk.Label(win,text="tabla")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="S                      P                   S→P")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      F                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)

def abrirventana49():
        win=tk.Toplevel()
        win.geometry("400x400+400+400")
        win.configure(background="dark turquoise")
        boton2=tk.Button(win,text="close",command=win.destroy)
        boton2.pack(side=tk.TOP)
        e3=tk.Label(win,text="tabla")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="S                      R                   S→R")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      F                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
#----------  (<->)
def abrirventana50():
        win=tk.Toplevel()
        win.geometry("400x400+400+400")
        win.configure(background="dark turquoise")
        boton2=tk.Button(win,text="close",command=win.destroy)
        boton2.pack(side=tk.TOP)
        e3=tk.Label(win,text="tabla")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="P                      Q                   P↔Q")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      V                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      F                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)

def abrirventana51():
        win=tk.Toplevel()
        win.geometry("400x400+400+400")
        win.configure(background="dark turquoise")
        boton2=tk.Button(win,text="close",command=win.destroy)
        boton2.pack(side=tk.TOP)
        e3=tk.Label(win,text="tabla")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="P                      R                   P↔R")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      V                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      F                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)

def abrirventana52():
        win=tk.Toplevel()
        win.geometry("400x400+400+400")
        win.configure(background="dark turquoise")
        boton2=tk.Button(win,text="close",command=win.destroy)
        boton2.pack(side=tk.TOP)
        e3=tk.Label(win,text="tabla")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="P                      S                   P↔S")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      V                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      F                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)

def abrirventana53():
        win=tk.Toplevel()
        win.geometry("400x400+400+400")
        win.configure(background="dark turquoise")
        boton2=tk.Button(win,text="close",command=win.destroy)
        boton2.pack(side=tk.TOP)
        e3=tk.Label(win,text="tabla")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="Q                      P                   Q↔P")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      V                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      F                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)

def abrirventana54():
        win=tk.Toplevel()
        win.geometry("400x400+400+400")
        win.configure(background="dark turquoise")
        boton2=tk.Button(win,text="close",command=win.destroy)
        boton2.pack(side=tk.TOP)
        e3=tk.Label(win,text="tabla")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="Q                      R                   Q↔R")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      V                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      F                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
def abrirventana55():
        win=tk.Toplevel()
        win.geometry("400x400+400+400")
        win.configure(background="dark turquoise")
        boton2=tk.Button(win,text="close",command=win.destroy)
        boton2.pack(side=tk.TOP)
        e3=tk.Label(win,text="tabla")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="Q                      S                   Q↔S")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      V                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      F                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
def abrirventana56():
        win=tk.Toplevel()
        win.geometry("400x400+400+400")
        win.configure(background="dark turquoise")
        boton2=tk.Button(win,text="close",command=win.destroy)
        boton2.pack(side=tk.TOP)
        e3=tk.Label(win,text="tabla")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="R                      Q                   R↔Q")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      V                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      F                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
def abrirventana57():
        win=tk.Toplevel()
        win.geometry("400x400+400+400")
        win.configure(background="dark turquoise")
        boton2=tk.Button(win,text="close",command=win.destroy)
        boton2.pack(side=tk.TOP)
        e3=tk.Label(win,text="tabla")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="R                      P                   R↔P")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      V                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
def abrirventana58():
        win=tk.Toplevel()
        win.geometry("400x400+400+400")
        win.configure(background="dark turquoise")
        boton2=tk.Button(win,text="close",command=win.destroy)
        boton2.pack(side=tk.TOP)
        e3=tk.Label(win,text="tabla")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="R                      S                   R↔S")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      V                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      F                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
def abrirventana59():
        win=tk.Toplevel()
        win.geometry("400x400+400+400")
        win.configure(background="dark turquoise")
        boton2=tk.Button(win,text="close",command=win.destroy)
        boton2.pack(side=tk.TOP)
        e3=tk.Label(win,text="tabla")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="S                      Q                   S↔Q")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      V                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      F                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
def abrirventana60():
        win=tk.Toplevel()
        win.geometry("400x400+400+400")
        win.configure(background="dark turquoise")
        boton2=tk.Button(win,text="close",command=win.destroy)
        boton2.pack(side=tk.TOP)
        e3=tk.Label(win,text="tabla")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="S                      P                   S↔P")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      V                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      F                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)

def abrirventana61():
        win=tk.Toplevel()
        win.geometry("400x400+400+400")
        win.configure(background="dark turquoise")
        boton2=tk.Button(win,text="close",command=win.destroy)
        boton2.pack(side=tk.TOP)
        e3=tk.Label(win,text="tabla")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="S                      R                   S↔R")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      F                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="F                      V                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      F                     F")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)
        e3=tk.Label(win,text="V                      V                     V")
        e3.pack(padx=5,pady=5,ipadx=5,ipady=5,fill=tk.X)

def cerrarventana():
    ventana.destroy()

ventana=tk.Tk()
ventana.title("ventana 1")
ventana.geometry("400x400")
ventana.configure(background="indianred")


def btnClik(num):
    global operador
    operador=operador+str(num)
    input_text.set(operador) #ESTA PARTE SIRVE PARA VISUALIZAR LA OPERACION EN LA PANTALLA

input_text=tk.StringVar()

def clear():
    global operador
    operador=("")
    input_text.set("0")

ancho_boton=11
alto_boton=2
color_boton=("sandybrown")
operador=""
Boton0=tk.Button(ventana,text="=",bg=color_boton,width=ancho_boton,height=alto_boton,command=validar).place(x=17,y=80)
Boton2=tk.Button(ventana,text="AC",bg=color_boton,width=ancho_boton,height=alto_boton,command=clear).place(x=287,y=80)
Boton3=tk.Button(ventana,text="P",bg=color_boton,width=ancho_boton,height=alto_boton,command=lambda:btnClik("P")).place(x=17,y=140)
Boton4=tk.Button(ventana,text="Q",bg=color_boton,width=ancho_boton,height=alto_boton,command=lambda:btnClik("Q")).place(x=107,y=140)
Boton5=tk.Button(ventana,text="R",bg=color_boton,width=ancho_boton,height=alto_boton,command=lambda:btnClik("R")).place(x=197,y=140)
Boton6=tk.Button(ventana,text="S",bg=color_boton,width=ancho_boton,height=alto_boton,command=lambda:btnClik("S")).place(x=287,y=140)
Boton7=tk.Button(ventana,text="῀",bg=color_boton,width=ancho_boton,height=alto_boton,command=lambda:btnClik("῀")).place(x=17,y=260)
Boton8=tk.Button(ventana,text="^",bg=color_boton,width=ancho_boton,height=alto_boton,command=lambda:btnClik("^")).place(x=107,y=200)
Boton9=tk.Button(ventana,text="V",bg=color_boton,width=ancho_boton,height=alto_boton,command=lambda:btnClik("V")).place(x=197,y=200)
Boton10=tk.Button(ventana,text="→",bg=color_boton,width=ancho_boton,height=alto_boton,command=lambda:btnClik("→")).place(x=287,y=200)
Boton11=tk.Button(ventana,text="↔",bg=color_boton,width=ancho_boton,height=alto_boton,command=lambda:btnClik("↔")).place(x=17,y=200)
Boton12=tk.Button(ventana,text="+",bg=color_boton,width=ancho_boton,height=alto_boton,command=lambda:btnClik("+")).place(x=107,y=260)
Boton13=tk.Button(ventana,text="(",bg=color_boton,width=ancho_boton,height=alto_boton,command=lambda:btnClik("(")).place(x=197,y=260)
Boton14=tk.Button(ventana,text=")",bg=color_boton,width=ancho_boton,height=alto_boton,command=lambda:btnClik(")")).place(x=287,y=260)

#entrada1=tk.Entry(ventana, font=("Comic Sans MS", 20, "bold"), width=22, textvariable=input_text, bd=10, insertwidth=4, bg="white", justify="right").place(x=10, y=10)
entrada1=tk.Entry(ventana,textvariable=input_text,bg="sandybrown")
entrada1.pack(fill=tk.X,padx=10,pady=10,ipadx=10,ipady=10)
ventana.mainloop()

